// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ6MDQfiRnAIfA6_zPtwsysvC2olbBXII',
    appId: '1:869381830751:web:0e49e4381cf835391283ea',
    messagingSenderId: '869381830751',
    projectId: 'pizza-delivery-3409f',
    authDomain: 'pizza-delivery-3409f.firebaseapp.com',
    storageBucket: 'pizza-delivery-3409f.firebasestorage.app',
    measurementId: 'G-2PVVTLY8N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuaWwdI9lBpQLTGaxobBkdmgzEY8vUjm8',
    appId: '1:869381830751:android:f783ee2eb2bf98b31283ea',
    messagingSenderId: '869381830751',
    projectId: 'pizza-delivery-3409f',
    storageBucket: 'pizza-delivery-3409f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU-cO6RZsbB1HbLj0XDxnCnYZQaPnyYEk',
    appId: '1:869381830751:ios:dd695ee3d072f60a1283ea',
    messagingSenderId: '869381830751',
    projectId: 'pizza-delivery-3409f',
    storageBucket: 'pizza-delivery-3409f.firebasestorage.app',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU-cO6RZsbB1HbLj0XDxnCnYZQaPnyYEk',
    appId: '1:869381830751:ios:dd695ee3d072f60a1283ea',
    messagingSenderId: '869381830751',
    projectId: 'pizza-delivery-3409f',
    storageBucket: 'pizza-delivery-3409f.firebasestorage.app',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZ6MDQfiRnAIfA6_zPtwsysvC2olbBXII',
    appId: '1:869381830751:web:700bbfbf4c36dbcc1283ea',
    messagingSenderId: '869381830751',
    projectId: 'pizza-delivery-3409f',
    authDomain: 'pizza-delivery-3409f.firebaseapp.com',
    storageBucket: 'pizza-delivery-3409f.firebasestorage.app',
    measurementId: 'G-57R2NTFN16',
  );
}
